version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ids-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ids-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
